FROM node:20-alpine AS build
WORKDIR /repo

COPY package*.json ./

RUN npm config set fetch-timeout 600000 \
    && npm config set fetch-retries 5 \
    && npm ci --prefer-offline --no-audit --no-fund

COPY . .

RUN npx nx build frontend --configuration=production

FROM nginx:alpine
COPY --from=build /repo/dist/apps/frontend /usr/share/nginx/html

RUN sed -i 's/try_files \$uri \$uri\/ =404;/try_files \$uri \/index.html;/' /etc/nginx/conf.d/default.conf

EXPOSE 80
